version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sprobe-course-be:latest
    container_name: sprobe-course-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    ports:
      - "9000:9000"
    command: sh -c "composer install && php artisan migrate && php-fpm"

  webserver:
    image: nginx:latest
    container_name: sprobe-course-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sprobe-course.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: sprobe-course-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sprobe_course
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
